const books = [
    {id: 1, 
        title: 'ES6 & BEYOND', 
        author: 'Kyle Simpson', 
        year:2016, 
        publisher: 'O\'Reilly Media', 
        language: 'English',
        isbn:  9352134192},
    {id: 2, 
        title: 'ASYNC & PERFORMANCE', 
        author: 'Kyle Simpson', 
        year:2015, 
        publisher:'O\'Reilly Media', 
        language: 'English',
        isbn: 9781491904220},
    {id: 3, 
        title: 'TYPES & GRAMMAR', 
        author: 'Kyle Simpson', 
        year:2015, 
        publisher:'O\'Reilly Media', 
        language: 'English',
        isbn: 9781491904190},
    {id: 4, 
        title: 'this & OBJECT PROTOTYPES', 
        author: 'Kyle Simpson', 
        year:2014,
        publisher:'O\'Reilly Media', 
        language: 'English',
        isbn: 9781491904152},
    {id: 5, 
        title: 'SCOPE & CLOSURES', 
        author: 'Kyle Simpson', 
        year:2014, 
        publisher:'O\'Reilly Media', 
        language: 'English',
        isbn: 9781449335588},
    {id: 6, 
        title: 'UP & GOING', 
        author: 'Kyle Simpson', 
        year:2015, 
        publisher:'O\'Reilly Media', 
        language: 'English',
        isbn: 9781491924464}

]


export default books;